### ISSUE TITLE
loading data error

### ISSUE THREAD

**Issue by Ian09** [quark0/darts#26]
Hi,

When I run the code on CIFAR10, `CUDA_VISIBLE_DEVICES=0 python train_search.py --unrolled`,
there is strange error which is
`
07/31 05:43:39 PM train 050 1.986851e+00 26.960785 81.188728
07/31 05:52:04 PM train 100 1.871319e+00 29.965965 84.189354
07/31 06:00:27 PM train 150 1.797943e+00 32.926323 85.844368
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc27522edd8>>
Traceback (most recent call last):
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/data1/yinzheng/anaconda2/envs/py36/lib/python3.6/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer
`
Can you tell me what is wrong with this error?
Thanks very much

**Comment by quark0** [comment]
I can't reproduce the error. I'd first tweak the options in `DataLoader`, e.g. `num_workers`.

**Comment by Ian09** [comment]
hi, 

It seems setting num_worker to 1 (default is 2) is fine. However, this error does not appear on train.py (not search), even it sets num_worker=2. BTW, I use pytorch 0.4.1, will the version cause the problem?

Thanks!

**Comment by quark0** [comment]
Perhaps `num_worker=1` would also work. I see similar issues being discussed [here](https://github.com/pytorch/pytorch/issues/1355) where people are posting their workarounds. I'm not sure but this appears to be a bug of pytorch, including v0.4.
