### ISSUE TITLE
Bug!DataLoaderIter ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by zihaozhang9** [quark0/darts#95]
I use `cd cnn && python train_search.py --unrolled     # for conv cells on CIFAR-10`
Get: 

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7ff940e565c0>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/opt/conda/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/opt/conda/lib/python3.6/multiprocessing/reduction.py", line 153, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_LEN(bytes_size))
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by MandyMo** [comment]
I reimplement a the CNN part that support latest Pytorch, and the code is available at https://github.com/MandyMo/DARTS.

**Comment by zihaozhang9** [comment]
> I reimplement a the CNN part that support latest Pytorch, and the code is available at https://github.com/MandyMo/DARTS.

ok!very thanks~
